[Router]: Info: Start to listen on port 31254
[Router]: Info: Client :0 connected, with message ClientRequestServer
[Router]: Info: Client :0 sent message ClientRequestServer with URL /service/2.1.2.1/SiliconStudio.Xenko.EffectCompilerServer.exe?mode=gamestudio&packageid=348b4819-b3de-44a6-a092-1c308e6baa87
[SiliconStudio.Xenko.EffectCompilerServer:10352]: Info: Process started
[Router]: Info: Client :0 connected, with message ServiceProvideServer
[Router]: Info: Client :0 connected, with message ServerStarted
[SiliconStudio.Xenko.EffectCompilerServer:10352]: Info: GameStudio mode started!
[Router]: Info: Client :0 disconnected with exception.. System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Xenko.ConnectionRouter.Router.<ForwardSocket>d__11.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.Xenko.ConnectionRouter\Router.cs:line 385
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SiliconStudio.Xenko.ConnectionRouter.Router.<HandleMessageClientRequestServer>d__6.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.Xenko.ConnectionRouter\Router.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Xenko.ConnectionRouter.Router.<>c__DisplayClass5_0.<<CreateSocketContext>b__1>d.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.Xenko.ConnectionRouter\Router.cs:line 79
System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Xenko.ConnectionRouter.Router.<ForwardSocket>d__11.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.Xenko.ConnectionRouter\Router.cs:line 385
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at SiliconStudio.Xenko.ConnectionRouter.Router.<HandleMessageClientRequestServer>d__6.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.Xenko.ConnectionRouter\Router.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at SiliconStudio.Xenko.ConnectionRouter.Router.<>c__DisplayClass5_0.<<CreateSocketContext>b__1>d.MoveNext() in C:\TeamCity\work\80a49494ba341a6a\sources\tools\SiliconStudio.Xenko.ConnectionRouter\Router.cs:line 79
